name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # Every hour
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: swayam7024
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
