name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }]
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # Required for API access
          user: swayam7024
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          repositories_affiliations: owner, collaborator, organization_member
          plugin_isocalendar: yes
          plugin_languages: yes
